apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-spot-cluster
  region: us-west-2

vpc:
  id: "vpc-02ac1d325f65044e7"
  cidr: "10.0.0.0/16"
  subnets:
    public:
      us-east-1a: { id: subnet-01b14c1e4852d1c61 }
      us-east-1b: { id: subnet-053f3238a14544d29 }

managedNodeGroups:
  - name: ng-db
    instanceType: t3.small
    labels: { role: builders }
    minSize: 2
    maxSize: 2
    ssh: 
      allow: true
      publicKeyName: eks-prep
    tags:
      Name: ng-db
        #  - name: ng-spot
        # instanceType: t3.medium
        # labels: { role: builders }
        #  minSize: 3
        # maxSize: 6
        # spot: true
        # ssh: 
        # allow: true
        # publicKeyName: techiescamp
        # tags:
        # Name: ng-spot
